#docker-compose.yml
version: '3.3'

services:
  synapse:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: synapse_core
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./data:/app/data
      - ./nginx:/app/nginx
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  nginx-sites:
    image: nginx:alpine
    container_name: nginx-sites
    env_file:
      - .env
    volumes:
      - ${HOST_PROJECT_PATH}/storage:/var/www/html:ro
      - ./nginx/:/etc/nginx/conf.d:ro
    ports:
      - "8091-8101:8091-8101"
    restart: always