#docker-compose.yml
version: '3.3'

services:
  synapse:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: synapse_core
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./data:/app/data
    restart: always